# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  title: GA4GH Workflow Execution API
  description: 'Proposed API for GA4GH workflow execution. A workflow is defined with a given format (currently CWL or WDL) and can encompass a single tool execution or a complex DAG of individual tool calls. The parameterization of the workflow called will follow the schema proposed in this group as a common format used for WDL and CWL execution'
  version: 0.1.0
  
produces:
  - application/json

tags:
  - name: GA4GH-workflow-execution
    description: A set of resources proposed as a common standard for workflow execution

# Describe your paths here
paths:
  /run:
    # This is a HTTP operation
    post:
      consumes:
        - application/json
      # Describe this verb here. Note: you can use markdown
      description: |
        Submit launch of a workflow
      tags:
        - GA4GH-workflow-execution
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - in: query
          name: wf
          description: URL to descriptor for workflow
          required: true
          type: string
        - in: formData
          name: body
          description: parameters for the workflow
          required: true
          type: file
            
      # Expected responses for this operation:
      responses:
        # Response code
        303:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
  /jobs/{jobId}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Get status for a workflow
      tags:
        - GA4GH-workflow-execution
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in path and is required
        -
          name: jobId
          in: path
          description: unique identifier for a workflow-run
          required: true
          type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Description of job including its status
          schema:
            $ref: '#/definitions/JobStatus'
            
definitions:
  JobStatus:
    type: object
    properties:
      run:
        type: string
        description: URL to the descriptor that was run
      input:
        type: object
        description: JSON parameter file for the run
      output:
        type: string
        description: Snippet of stdout?
      state:
        type: string
        description: Current status for the job
        enum:
          - Running
          - Paused
          - Success
          - Failed
          - Cancelled
      log:
        type: string
        description: URL to get just he log for this job
            
          
